### ISSUE TITLE
כמות גשם is always 0.0 despite there were lots of rains for station

### ISSUE THREAD

**Issue by vadimnazaroff** [GuyKh/ims-envista-custom-component#23]
### System Health details

v0.0.11 (Observed on previous versions as well)

### Checklist

- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of any [previous issues](https://github.com/ludeeus/integration_blueprint/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

כמות גשם is always 0.0 despite there were lots of rains for station

### Reproduction steps

1. Check history of כמות גשם for your station for last 3 weeks 
2. value is always 0.0
3.
...

![image](https://github.com/user-attachments/assets/d12bb697-c1b7-4422-b2b5-7a28b9a2c16f)

### Debug logs

```text
N/A
```

**Comment by vadimnazaroff** [comment]
![image](https://github.com/user-attachments/assets/81c554c6-98fb-4ad3-b801-c0fd2c2b8c4e)

Evidence for rains for station

**Comment by GuyKh** [comment]
Please note that you're sharing different data types;

In the integration, I'm pulling every 10 mins the latest station data (i.e. 10min resolution).
In the image you shared - you see an aggregated data (Daily, etc).

Here's a scenario:
Every hour, the station publishes data for the last hour. Because of IMS standards, these are in resolutions of 10 mins, but the last 10 mins were **without rain**.
So, in HomeAssistant, you'll see an update **every hour** with rain = 0 (as its taking the last 10 mins of every hour data).

This is my hypothesis.
Can you check the "Last Time Updated" - to see the update rate?
And specify please the station number and date (with rain)

**Comment by vadimnazaroff** [comment]
If your hypothesis is correct, then this sensor quite useless, as it almost never will show valuable data. Does Envista API expose daily accumulation, which in this case will be more valuable? 
In any case during last 3 weeks there were quite a lot of rains, statistically we should see at least once value bigger that 0.0, for instance last 2 days there were showers longer than 1h in duration.... 
Station is 24 (Newe Yaar), i did integration reload like 15 min after rain was over to make sure there is no lack of data load. 

![image](https://github.com/user-attachments/assets/6b8b709f-3841-4405-8e90-02be37d5edc7)

**Comment by GuyKh** [comment]
As you can see on - "Last Update" - it's 2 hrs ago...

It's not about this not being useful or not it's about which station updates how often...

**Comment by GuyKh** [comment]
Here's more clear example - You can see that the frequency of updated data **coming from IMS Envista station** - although trying to fetch every 10 mins is about once in an hour or more:
![image](https://github.com/user-attachments/assets/90aec709-1f12-4b5b-8362-5eed48514b64)

And as such, data updates and especially **frequency** regarding changes may vary - 
e.g. - look how often the data changed yesterday vs today:
![image](https://github.com/user-attachments/assets/cbae199f-3f31-46d4-849e-c2f5ffe662eb)


I completely understand your concerns, but this is out of my control

**Comment by vadimnazaroff** [comment]
I see, thanks Guy!
